### ISSUE TITLE
Add support for R

### ISSUE THREAD

**Issue by raxod502** [radian-software/radian#170]
The [`ess`](https://ess.r-project.org/) package looks like a good candidate for this.

**Comment by raxod502** [comment]
In order to support R Markdown, we'll also need:

- [pandoc](http://pandoc.org/)
- [polymode](https://github.com/vspinu/polymode)

See also:

- http://stackoverflow.com/q/16172345/3538165
- http://stackoverflow.com/q/28324288/3538165

Plus, the setup script will need to ensure that R is installed, and install any necessary packages for processing R Markdown.

**Comment by raxod502** [comment]
Closing for the moment as I thankfully don't have to deal with R anymore. If you want it, please comment.

**Comment by yizhexu** [comment]
Hey! Need R support. Don't need R markdown, just need R syntax + org babel, can you comment on how one might go about adding it to radian?

**Comment by raxod502** [comment]
I'd suggest looking at some of the other languages that are supported, e.g. [any sub-section under Languages](https://github.com/raxod502/radian/blob/06f4050491bb2d93162b9a1cd3ccc72a1dcdc9e1/emacs/radian.el#L2671). R would be no different. The configuration for package management is self-contained, so you just need to add the relevant `use-package` forms under a new section and then `:config` away.

I would start with `(use-package ess)` and go from there. Good luck!

**Comment by raxod502** [comment]
Closing as stale. I don't use R, and am unlikely to work on this.
