### ISSUE TITLE
`M-x compile` default command should be major-mode dependent

### ISSUE THREAD

**Issue by redpanda1234** [radian-software/radian#399]
e.g., in rust-mode, should default to `cargo build`

**Comment by raxod502** [comment]
Sounds like a good idea. I didn't find any packages which do this except for [Mode Compile](https://www.emacswiki.org/emacs/ModeCompile), which is unmaintained. I think the best option would be to add an alist in `radian-compile.el` and some advice or hook which sets the default file-local value for `compile-command` based on the major mode and that alist. Then the configuration for other modes can add to that alist (for example, the `use-package` for `rust-mode` adds an item for `cargo build`).

**Comment by raxod502** [comment]
You can also just set `compilation-command` as a file-local or directory-local variable.

**Comment by raxod502** [comment]
Thinking on this 6 years later, I'm not sure this is something that's best to solve at the framework level. Different users may have significantly different preferences about what commands to use by default, and how to select them. I think this may be best to leave to the user's configuration.
