### ISSUE TITLE
Compilation based on make and bash does not work on Windows

### ISSUE THREAD

**Issue by Whil-** [radian-software/radian#458]
The compilation process that is set up using make and bash does not work well with windows. Relying on make and bash-scripts for compilation as is done in `radian-byte-compile` will break in 99% of windows users configurations. Either it should only be active on non-windows machines or some kind of conditional logic is needed to determine how to do the external compilation.

This was mentioned in issue #457 as well, but extracted here for "issue-atomicity". ;)

**Comment by raxod502** [comment]
Windows users can now disable byte-compilation by adding `bytecomp` to `radian-disabled-features`.
