### ISSUE TITLE
Failed to byte-compile: Debugger entered--Lisp error: (error "Building straight not allowed in safe mode")

### ISSUE THREAD

**Issue by hrehfeld** [radian-software/radian#483]
During startup on first run. Sadly no backtrace even though I started with `--debug-init`. With:

```
$ emacs --version
GNU Emacs 28.0.50
```
(with GCCJIT)

radian just pulled:
```
$ git log
c508178ae1d8483985bf9446074d64fcbc0e3f4e
```

`straight-safe-mode` is `nil` after startup.

Doesn't seem to happen when starting a second time.

**Comment by raxod502** [comment]
You can try deleting `~/.emacs.d/straight/build` as well as `radian/emacs/radian.elc`, and seeing if the error happens again. If so, we can investigate further. If not, it's probably not worth tracking down.

**Comment by hrehfeld** [comment]
Hmm, hasn't occured to me in a long while, but I don't remember what I did :ocean:
