### ISSUE TITLE
Aggregate global Radian keybindings into minor mode map

### ISSUE THREAD

**Issue by hrehfeld** [radian-software/radian#485]
We could also take this one step further and create modes for each feature:

`radian-mwheel-mode-map` etc.

**Comment by raxod502** [comment]
For global keybindings, that seems reasonable, the only thing is we have to be careful with testing, since minor modes have precedence rules that are quite different from the global keymap.

**Comment by raxod502** [comment]
All Radian bindings are now in `radian-keymap`, which is bound on a prefix. I don't think we get a lot more out of putting that single prefix binding into a keymap of its own; `bind-key*` actually does that transparently. But let me know if you disagree.

**Comment by hrehfeld** [comment]
Awesome, thanks!

28 Feb 2023 06:20:17 Radon Rosborough ***@***.***>:
