### ISSUE TITLE
radian-bind-key is an unnecessary dependency on "frameworky" code

### ISSUE THREAD

**Issue by hrehfeld** [radian-software/radian#488]
https://github.com/raxod502/radian/blob/develop/emacs/radian.el#L670

Instead of having to remember the name of the `radian-keymap` you now have to remember the name of the `radian-bind-key` function, and severely reduce composability.

**Comment by raxod502** [comment]
Hmmm... but nothing stops you from binding directly in `radian-keymap`, does it? The point of the macro is just to save a few characters.

**Comment by hrehfeld** [comment]
:+1: thank you!

28 Feb 2023 05:15:28 Radon Rosborough ***@***.***>:
