### ISSUE TITLE
Prevent loading of outdated org files

### ISSUE THREAD

**Issue by haji-ali** [radian-software/radian#508]
In `radian.el`, there are two lines that are supposed to prevent loading of outdated `org` files that come shipped with emacs. 
https://github.com/radian-software/radian/blob/b86946f9d87060d81dc04c1d00a14c8b9d576739/emacs/radian.el#L689-L690

This works well if one uses `(use-package 'org)` to load `org`. However, if I load a package which requires `org` using the traditional `(require 'org)` then the old org packages are loaded instead. This is because the `load-path` is updated only when `(use-package 'org)` is called.

What is the correct way to handle this? I currently have the command `(use-package 'org)` in the top of my local init file, but I am wondering if such a statement should be included in radian instead.

**Comment by haji-ali** [comment]
PS: I also noticed that the `load-path` is not set correctly if a file containing a `use-package` is compiled without being loaded first. These compilation/path dependencies are driving me insane.

**Comment by raxod502** [comment]
Such a statement is, in fact, included in Radian: https://github.com/raxod502/radian/blob/68e7fd41a20429456a1938430e6e13e6c0a3029b/emacs/radian.el#L4079

You're definitely right about the potential for an edge case where a package loads Org, but doesn't declare a dependency on it. However, this doesn't appear to be the case for any of the packages loaded in Radian, so we should be safe at least in the current state of the world. If you load a package in your local init-file, then it will come in after everything from Radian is loaded, so the Org from `straight.el` should already be loaded. (Assuming that you're installing your configurations within `radian-local-on-hook after-init`.)

**Comment by haji-ali** [comment]
I honestly can’t remember the issue I was mentioning here. Apologies.

Closing this for now while I investigate. Will reopen if I come up with something.

**Comment by raxod502** [comment]
No worries!
