### ISSUE TITLE
vertico--update-candidates is not defined

### ISSUE THREAD

**Issue by haji-ali** [radian-software/radian#520]
It seems that `vertico--update-candidates` is no longer defined in vertico (replaced by `vertico--update`?)
Perhaps the advice `radian--advice-vertico-select-first-candidate` should also be removed/updated? (I don't personally use it, but it makes compilation on emacs 29 fail)

**Comment by raxod502** [comment]
Indeed:

https://github.com/minad/vertico/commit/e76f30f7bdea5da1ad7bec629f8b24efc334ec2c
https://github.com/minad/vertico/commit/0baa4c2d45442a1cccfd6b15c5a8c687cb61f0a0

Thanks for the report.
