### ISSUE TITLE
Is there a way to register radian definitions correctly?

### ISSUE THREAD

**Issue by haji-ali** [radian-software/radian#522]
I like that Radian compiles my config file as part of radian.el (in fact I made a change to Radian's code to compile all files in a custom init directory as part of radian.el).

However, one problem is that all functions/variables are registered to have their definition in radian.el rather than in the correct file where they were defined. I know that the compilation process of radian embeds my init files as part of radian.el, but I am wondering  if there is some emacs-wizardy that we can do to correct for this issue.

Thoughts?

**Comment by raxod502** [comment]
Huh, you're right. I had never even noticed.

**Comment by haji-ali** [comment]
That's much better thanks!

I am still seeing package functions like `no-littering-expand-var-file-name` being shown to be defined in `radian.el` (for example if I call `helpful-function` on it. 
Is it just me?

I am not 100% what the cause is, except that `no-littering-expand-var-file-name` appears twice in `load-history`.

This is the value of `load-history`:

```
(...

(".../radian/emacs/radian.elc"
   ...
   (defun . no-littering-expand-etc-file-name)
   (defun . no-littering-expand-var-file-name)
   (provide . no-littering-autoloads)
  ...)
...
(".../straight/build-29.0.90/no-littering/no-littering.elc"
  (require . cl-lib)
  (require . compat)
  no-littering-etc-directory no-littering-var-directory
  (defun . no-littering-expand-etc-file-name)
  (defun . no-littering-expand-var-file-name)
  (provide . no-littering))
...) 
```

Maybe there's an issue with autoloads being considered the true definition? Not sure this is radian related or use-package related.

**Comment by haji-ali** [comment]
Sorry for the noise. Radian is behaving as expected.  
Emacs needs a better way of finding the source of a function that is being autoloaded.
